
name: Node.js Package
on:
   push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish new version to NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
